# Generated by Django 5.0.6 on 2024-06-25 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_customers_address2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='is_cancled',
            new_name='is_cancelled',
        ),
    ]
