# Generated by Django 5.0.6 on 2024-06-25 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_is_cancled_orders_is_cancelled'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderDetails',
            new_name='OrderDetail',
        ),
    ]
