# Generated by Django 5.0.6 on 2024-06-25 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_orderdetails_orderdetail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customers',
            new_name='Customer',
        ),
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
