# Generated by Django 5.0.6 on 2024-06-28 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_customers_customer_rename_orders_order'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderdetail',
            unique_together={('order_number', 'product_id')},
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='customer_id',
        ),
    ]
